[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "fastfetch"

[[session]]
name = "Documents ğŸ“"
path = "~/Documents"
startup_command = "fastfetch"

[[session]]
name = "sesh-config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "ObsidianNotes"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Handes"
startup_command = "nvim 'Entry Notes.md'"

[[session]]
name = "nvim"
path = "~/.config/nvim"
startup_command = "nvim init.lua"

[[session]]
name = "default"
path = "~"

[[session]]
name = "spotify"
path = "~"
startup_command = "spotify-player"
