[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "ll"

[[session]]
name = "Documents ğŸ“"
path = "~/Documents"
startup_command = "ll"

[[session]]
name = "sesh-config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "ObsidianNotes"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Handes"
startup_command = "nvim 'Entry Notes.md'"
